version: "3.8"
services:
  sandboxdocker:
    image: sandboxdocker:latest
    container_name: sandboxdocker
    restart: always
    tty: true
    working_dir: /root/ext_volume
    environment:
      INTERNAL_LLM_API_BASE: "http://host.docker.internal:11434/v1"
      INTERNAL_LLM_API_KEY: "dev-key"
    volumes:
      - ${HOME}:/root/ext_volume
    ports:
      - "37910:37910"
      - "37911:37911"
      - "37912:37912"
      - "37913:37913"
      - "37914:37914"
      - "37915:37915"
      - "38010:38010"
      - "38011:38011"
